In [10]:
import pandas as pd
import plotly.express as px
import nbformat

In [11]:
df = pd.read_csv("country_wise_latest.csv")
df

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [12]:
top_10 = df.nlargest(10, 'Confirmed')
fig = px.bar(top_10, x='Country/Region', y='Confirmed', title='Top 10 countries with highest confirmed cases', text='Confirmed', color='Confirmed', template='plotly_dark')
fig.update_traces(textposition='outside')
fig.show()

In [13]:
fig = px.pie(df, names = 'WHO Region', values = 'Confirmed', title = 'Confirmed cases per WHO region', template = 'plotly_dark', color_discrete_sequence = px.colors.sequential.Rainbow, height = 500, width = 800)
fig.show()

In [14]:
trendline =  df.sort_values(by='1 week % increase', ascending=False).head(20) # this will sort the data by 1% increase in descending order and select top 20 

fig = px.line(trendline, x = 'Country/Region', y = '1 week % increase', title = 'Weekly % increase in COVID-19 cases', template = 'plotly_dark', markers = True, width=800, height=500)
fig.update_traces(marker=dict(size=8, symbol='circle-open'))
fig.show()

In [15]:
df

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [17]:
fig = px.scatter(df, x = 'Confirmed', y = 'Deaths', color = 'WHO Region', size = 'Confirmed', title = 'Confirmed cases vs Deaths', template = 'plotly_dark', height = 800, width = 800, hover_name = 'Country/Region')
fig.show()

In [1]:
import streamlit as st